name: Generar EPG Bravo

on:
  schedule:
    - cron: '0 5 * * *' # Se ejecuta todos los días a las 5am UTC
  workflow_dispatch: # Botón para ejecutar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar librería requests
      run: pip install requests

    - name: Ejecutar generador
      run: python main.py

    - name: Subir resultado
      uses: actions/upload-artifact@v4  # <--- AQUÍ ESTÁ LA CORRECCIÓN (v4)
      with:
        name: mi-guia-xml
        path: guia.xml.gz
