name: Update EPG

on:
  schedule:
    - cron: '0 */12 * * *'   # Cada 12 horas
  workflow_dispatch:         # Permite ejecutar manualmente

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configurar Git con PAT
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.MY_PAT }}@github.com/${{ github.repository }}.git

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Generar guía 72h
        # Pasamos las llaves de API de TMDB y las 8 OpenAI Keys de forma segura
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          OPENAI_API_KEY_1: ${{ secrets.OPENAI_API_KEY_1 }}
          OPENAI_API_KEY_2: ${{ secrets.OPENAI_API_KEY_2 }}
          OPENAI_API_KEY_3: ${{ secrets.OPENAI_API_KEY_3 }}
          OPENAI_API_KEY_4: ${{ secrets.OPENAI_API_KEY_4 }}
          OPENAI_API_KEY_5: ${{ secrets.OPENAI_API_KEY_5 }}
          OPENAI_API_KEY_6: ${{ secrets.OPENAI_API_KEY_6 }}
          OPENAI_API_KEY_7: ${{ secrets.OPENAI_API_KEY_7 }}
          OPENAI_API_KEY_8: ${{ secrets.OPENAI_API_KEY_8 }}
        run: python generate_epg.py

      - name: Hacer commit si hay cambios
        run: |
          git add guide_custom.xml guide_custom.xml.gz
          git diff-index --quiet HEAD || git commit -m "Actualizar guía 72h automáticamente"

      - name: Push cambios
        run: git push origin main
