name: Update EPG

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Clonar el repo y permitir push
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2️⃣ Instalar librerías de Node
      - name: Instalar Node y dependencias
        run: npm install fast-xml-parser

      # 3️⃣ Verificar archivos
      - name: Listar archivos
        run: ls -R sites/

      # 4️⃣ Generar guía 72h
      - name: Generar guía 72h
        run: node generate_72h.js

      # 5️⃣ Subir guía usando token seguro
      - name: Subir guía a GitHub
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
