name: Update EPG

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta cada 24 horas a medianoche
  workflow_dispatch:      # Permite ejecutarlo manualmente

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Clonar el repositorio
      - uses: actions/checkout@v3

      # 2️⃣ Instalar dependencias de Node (incluyendo fast-xml-parser)
      - name: Instalar Node y dependencias
        run: |
          npm install fast-xml-parser

      # 3️⃣ Generar guía 72h
      - name: Generar guía 72h
        run: node generate_72h.js

      # 4️⃣ Subir guía generada a GitHub
      - name: Subir guía a GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add guide_custom.xml
          git commit -m "Actualizar guía automáticamente" || echo "No hay cambios"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/dashbrox/my-filter.git HEAD:main
