name: Actualizar guía HBO

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *"   # cada 12 horas (0 UTC y 12 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Instalar PHP
        run: sudo apt-get update && sudo apt-get install -y php-cli

      - name: Ejecutar Tempest EPG Generator
        run: php tempest.php engine=Generate createxmlgz=on output=guide_custom.xml

      - name: Commit y push de cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add guide_custom.xml
          git commit -m "Actualizar guide_custom.xml $(date '+%Y-%m-%d %H:%M')" || echo "No hay cambios"
          git pull --rebase origin main || echo "No hay cambios remotos"
          git push
