name: Update EPG

on:
  schedule:
    - cron: '0 0 * * *'  # Cada 24 horas
  workflow_dispatch:      # Permite ejecutar manualmente

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Clonar el repo
      - uses: actions/checkout@v3

      # 2️⃣ Instalar librerías de Node
      - name: Instalar Node y dependencias
        run: npm install fast-xml-parser

      # 3️⃣ Verificar archivos (opcional para debug)
      - name: Listar archivos
        run: ls -R sites/

      # 4️⃣ Generar guía 72h
      - name: Generar guía 72h
        run: node generate_72h.js

      # 5️⃣ Subir guía usando token seguro
      - name: Subir guía a GitHub
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
