name: Actualizar guía HBO

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *"   # cada 12 horas (0 UTC y 12 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # necesario para permitir push con GITHUB_TOKEN

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # permite push automático

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar scraper HBO
        run: python scraper_mitv.py

      - name: Commit y push de cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add guide_custom.xml
          git commit -m "Actualizar guide_custom.xml $(date '+%Y-%m-%d %H:%M')" || echo "No hay cambios"
          git push
