name: Generar EPG con epg-grabber

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *" # cada 12 horas (00:00 y 12:00 UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Generar guía EPG
        run: npm run grab

      - name: Subir guía como artifact
        uses: actions/upload-artifact@v3
        with:
          name: guide
          path: guide.xml
