name: Update EPG

on:
  schedule:
    - cron: "0 */12 * * *"  # cada 12 horas
  workflow_dispatch:        # permite ejecución manual

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # necesario para que github-actions[bot] pueda hacer push

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade openai requests

      # -------------------- PRIMER RUN CON RESET --------------------
      - name: Ejecutar script EPG con RESET (solo la primera vez)
        if: github.ref == 'refs/heads/main' # opcional: limitar a main
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
          OPENAI_API_KEY_1: ${{ secrets.OPENAI_API_KEY_1 }}
          OPENAI_API_KEY_2: ${{ secrets.OPENAI_API_KEY_2 }}
          OPENAI_API_KEY_3: ${{ secrets.OPENAI_API_KEY_3 }}
          OPENAI_API_KEY_4: ${{ secrets.OPENAI_API_KEY_4 }}
          OPENAI_API_KEY_5: ${{ secrets.OPENAI_API_KEY_5 }}
          OPENAI_API_KEY_6: ${{ secrets.OPENAI_API_KEY_6 }}
          OPENAI_API_KEY_7: ${{ secrets.OPENAI_API_KEY_7 }}
          OPENAI_API_KEY_8: ${{ secrets.OPENAI_API_KEY_8 }}
        run: |
          echo "🚀 Ejecutando generate_epg.py con --reset (solo primera vez)..."
          python generate_epg.py --reset
          echo "✅ Script finalizado."

      # -------------------- RUNS FUTUROS SIN RESET --------------------
      - name: Ejecutar script EPG (normal)
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
          OPENAI_API_KEY_1: ${{ secrets.OPENAI_API_KEY_1 }}
          OPENAI_API_KEY_2: ${{ secrets.OPENAI_API_KEY_2 }}
          OPENAI_API_KEY_3: ${{ secrets.OPENAI_API_KEY_3 }}
          OPENAI_API_KEY_4: ${{ secrets.OPENAI_API_KEY_4 }}
          OPENAI_API_KEY_5: ${{ secrets.OPENAI_API_KEY_5 }}
          OPENAI_API_KEY_6: ${{ secrets.OPENAI_API_KEY_6 }}
          OPENAI_API_KEY_7: ${{ secrets.OPENAI_API_KEY_7 }}
          OPENAI_API_KEY_8: ${{ secrets.OPENAI_API_KEY_8 }}
        run: |
          echo "🚀 Ejecutando generate_epg.py..."
          python generate_epg.py
          echo "✅ Script finalizado."

      - name: Subir artefactos
        uses: actions/upload-artifact@v4
        with:
          name: epg-files
          path: |
            guide_custom.xml
            guide_custom.xml.gz
            epg_log.txt

      - name: Commit y Push resultados
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add guide_custom.xml guide_custom.xml.gz epg_cache.json epg_log.txt
          git commit -m "🔄 Actualización automática de EPG [skip ci]" || echo "No hay cambios"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
