name: Update EPG

on:
  schedule:
    - cron: '0 0 * * *'  # Cada 24 horas
  workflow_dispatch:      # Permite ejecutar manualmente

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio y permitir push
      - name: Clonar repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2️⃣ Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Instalar dependencias
      - name: Instalar dependencias
        run: npm install fast-xml-parser

      # 4️⃣ Listar archivos (opcional)
      - name: Listar archivos
        run: ls -R sites/

      # 5️⃣ Ejecutar tu script para generar guía
      - name: Generar guía 72h
        run: node generate_72h.js

      # 6️⃣ Configurar Git para commit
      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 7️⃣ Hacer commit solo si hay cambios
      - name: Hacer commit si hay cambios
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "Actualizar guía 72h automáticamente"

      # 8️⃣ Hacer push usando PAT
      - name: Push cambios con PAT
        run: |
          git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/${{ github.repository }}.git main
