name: Update EPG

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install fast-xml-parser

      - name: Generar guía 72h
        run: node generate_72h.js

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Hacer commit si hay cambios
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "Actualizar guía 72h automáticamente"

      - name: Push cambios con PAT
        run: |
          git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/${{ github.repository }}.git main
