name: Generar Tempest EPG

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Instalar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Clonar Tempest EPG
      run: git clone https://github.com/K-vanc/Tempest-EPG-Generator.git tempest

    - name: Crear carpeta output
      run: mkdir -p output

    - name: Generar guía
      run: |
        cd tempest
        # Asegúrate de que tempest.php exista o usa tu versión simplificada
        php tempest.php engine=Generate createxmlgz=on output=../output/guide_custom.xml

    - name: Verificar output
      run: ls -l output
